### ISSUE TITLE
 Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by ArjunReddy07** [AnthonyEbert/EasyMMD#6]
Hi,
 Please excuse me if the issue is trivial. I am not able to install the package with the given instructions, getting the error
 "Error: Failed to install 'unknown package' from GitHub:
  Failed to connect to api.github.com port 443: Connection refused"
I use the institute's internet and am behind a proxy, tried to install with proxy settings too.

**Comment by AnthonyEbert** [comment]
Hi, 

Can you try this `devtools::install_github("r-simmer/simmer")` and, if that works, try `devtools::install_github("AnthonyEbert/EasyMMD")`. If the first one doesn't work then it's not an EasyMMD issue. Sorry!

Good luck!
